services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./dozzle/.env
    ports:
      - 8080:8080/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle-data:/data

  prometheus-plex-exporter:
    container_name: prometheus-plex-exporter
    image: ghcr.io/timothystewart6/prometheus-plex-exporter:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./plex-prometheus-exporter/.env
    # ports:
    # - 9000:9000/tcp
    security_opt:
      - no-new-privileges:true
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    pull_policy: always
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows access to host network from container
    env_file:
      - ./prometheus/.env
    user: "1000:1000"
    ports:
      - 9090:9090/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - prometheus-data:/prometheus
      - prometheus-rules:/etc/prometheus/rules
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.enable-lifecycle    
      - --web.enable-admin-api
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./node-exporter/.env
    # ports:
    #   - 9100:9100
    security_opt:
      - no-new-privileges:true
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.cpu.info'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
  dcgm-exporter:
    image: nvidia/dcgm-exporter:4.3.1-4.4.1-ubuntu22.04
    container_name: dcgm-exporter
    pull_policy: always
    restart: unless-stopped
    gpus: all
    cap_add:
      - SYS_ADMIN
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./dcgm-exporter/.env
    # ports:
    #   - "9400:9400"
  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:latest
    container_name: smartctl-exporter
    pull_policy: always
    restart: unless-stopped
    privileged: true
    user: root
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - prometheus
    env_file:
      - ./grafana/.env
    user: "1000:1000"
    ports:
      - 3000:3000/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - grafana-data:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./cadvisor/.env
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

volumes:
  dozzle-data:
  prometheus-data:
  prometheus-rules:
  grafana-data:

